openapi: 3.0.0
info:
  title: Applicant API
  version: 1.0.0
paths:
  /applicant:
    get:
      summary: Get all applicants
      operationId: app.get_all_applicants
      responses:
        '200':
          description: A list of applicants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/applicant'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message404'
    post:
      summary: Create a new applicant
      operationId: app.create_applicant
      responses:
        '201':
          description: Created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/applicant'
  /applicant/{id}:
    get:
      summary: Get an applicant by ID
      operationId: app.get_applicant_by_id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The applicant ID
      responses:
        '200':
          description: An applicant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/applicant'
    put:
      summary: Update an applicant by ID
      operationId: app.update_applicant_by_id
      responses:
        '200':
          description: Updated
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The applicant ID
    delete:
      summary: Delete an applicant by ID
      operationId: app.delete_applicant_by_id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The applicant ID
      responses:
        '204':
          description: Deleted
  # /Applicant/Details/{id}:
  #   get:
  #     summary: Get details of an applicant
  #     operationId: getApplicantDetails
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: integer
  #     responses:
  #       '200':
  #         description: Details of an applicant
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Applicant'
  #       '404':
  #         description: Not found

  # /Applicant/Create:
  #   post:
  #     summary: Create a new applicant
  #     operationId: createApplicant
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/Applicant'
  #     responses:
  #       '201':
  #         description: Applicant created

  # /Applicant/Edit/{id}:
  #   post:
  #     summary: Edit an existing applicant
  #     operationId: editApplicant
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: integer
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/Applicant'
  #     responses:
  #       '200':
  #         description: Applicant updated
  #       '404':
  #         description: Not found

  # /Applicant/Delete/{id}:
  #   delete:
  #     summary: Delete an applicant
  #     operationId: deleteApplicant
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: integer
  #     responses:
  #       '200':
  #         description: Applicant deleted
  #       '404':
  #         description: Not found
components:
  schemas:
    applicant:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        employer:
          type: string
        income:
          type: number
        reference:
          $ref: '#/components/schemas/reference'
    reference:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        relationship:
          type: string
    asset:
      type: object
      properties:
        id:
          type: integer
        asset_type:
          type: string
        status:
          type: string
        location:
          type: string
        occupancy_history:
          type: array
          items:
            $ref: '#/components/schemas/occupancy'
        rent_history:
          type: array
          items:
            $ref: '#/components/schemas/rent'
        damage_history:
          type: array
          items:
            $ref: '#/components/schemas/damage'
        appliances:
          type: array
          items:
            $ref: '#/components/schemas/appliance'
    occupancy:
      type: object
      properties:
        id:
          type: integer
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        license_plate:
          type: string
    rent:
      type: object
      properties:
        id:
          type: integer
        change_date:
          type: string
          format: date
        amount:
          type: number
    damage:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        date_reported:
          type: string
          format: date
    appliance:
      type: object
      properties:
        id:
          type: integer
        brand:
          type: string
        model:
          type: string
    Message404:
      type: object
      properties:
        message:
          type: string
